package xstate_test

import (
	"encoding/json"
	"regexp"
	"testing"

	xs "github.com/nguyenvanduocit/go-xstate/xstate"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// id1IDMachine mirrors the top-level `idMachine` of id.test.ts (lines 9-54).
func id1IDMachine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "A",
		States: xs.States{
			{
				Key:     "A",
				ID:      "A",
				Initial: "foo",
				States: xs.States{
					{Key: "foo", ID: "A_foo", On: map[string]xs.Transitions{
						"NEXT": {{Target: "#A_bar"}},
					}},
					{Key: "bar", ID: "A_bar", On: map[string]xs.Transitions{
						"NEXT": {{Target: "#B_foo"}},
					}},
				},
				On: map[string]xs.Transitions{
					"NEXT_DOT_RESOLVE": {{Target: "#B.bar"}},
				},
			},
			{
				Key:     "B",
				ID:      "B",
				Initial: "foo",
				States: xs.States{
					{Key: "foo", ID: "B_foo", On: map[string]xs.Transitions{
						"NEXT":     {{Target: "#B_bar"}},
						"NEXT_DOT": {{Target: "#B.dot"}},
					}},
					{Key: "bar", ID: "B_bar", On: map[string]xs.Transitions{
						"NEXT": {{Target: "#A_foo"}},
					}},
					{Key: "dot"},
				},
			},
		},
	})
}

// id1ResolveSerializedStateValue mirrors resolveSerializedStateValue from
// test/utils.ts.
func id1ResolveSerializedStateValue(t *testing.T, machine *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized[0] == '{' {
		var value any
		require.NoError(t, json.Unmarshal([]byte(serialized), &value))
		return machine.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return machine.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

var id1EventSplit = regexp.MustCompile(`,\s?`)

// id1TestMultiTransition mirrors testMultiTransition from test/utils.ts.
func id1TestMultiTransition(t *testing.T, machine *xs.StateMachine[any], fromState string, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	state := id1ResolveSerializedStateValue(t, machine, fromState)
	for _, eventType := range id1EventSplit.Split(eventTypes, -1) {
		state = xs.GetNextSnapshot[*xs.MachineSnapshot[any]](machine, state, xs.Ev(eventType))
	}
	return state
}

// id1TestAllCase mirrors the body of each it() generated by testAll from
// test/utils.ts. toState == nil mirrors `undefined` (no transition).
func id1TestAllCase(t *testing.T, fromState string, eventTypes string, toState xs.StateValue) {
	t.Helper()
	machine := id1IDMachine()
	resultState := id1TestMultiTransition(t, machine, fromState, eventTypes)

	switch ts := toState.(type) {
	case nil:
		// undefined means that the state didn't transition
		assert.Equal(t, id1ResolveSerializedStateValue(t, machine, fromState).Value, resultState.Value)
	case string:
		assert.True(t, xs.MatchesState(ts, resultState.Value))
	default:
		assert.Equal(t, toState, resultState.Value)
	}
}

// JS: State node IDs > should go from A to {"A":"bar"} on NEXT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L59
func TestId_StateNodeIDs_ShouldGoFromAToABarOnNEXT(t *testing.T) {
	id1TestAllCase(t, "A", "NEXT", map[string]any{"A": "bar"})
}

// JS: State node IDs > should go from A to {"B":"bar"} on NEXT_DOT_RESOLVE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L60
func TestId_StateNodeIDs_ShouldGoFromAToBBarOnNEXT_DOT_RESOLVE(t *testing.T) {
	id1TestAllCase(t, "A", "NEXT_DOT_RESOLVE", map[string]any{"B": "bar"})
}

// JS: State node IDs > should go from {"A":"foo"} to {"A":"bar"} on NEXT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L63
func TestId_StateNodeIDs_ShouldGoFromAFooToABarOnNEXT(t *testing.T) {
	id1TestAllCase(t, `{"A":"foo"}`, "NEXT", map[string]any{"A": "bar"})
}

// JS: State node IDs > should go from {"A":"bar"} to {"B":"foo"} on NEXT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L66
func TestId_StateNodeIDs_ShouldGoFromABarToBFooOnNEXT(t *testing.T) {
	id1TestAllCase(t, `{"A":"bar"}`, "NEXT", map[string]any{"B": "foo"})
}

// JS: State node IDs > should go from {"B":"foo"} to {"A":"foo"} on NEXT,NEXT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L69
func TestId_StateNodeIDs_ShouldGoFromBFooToAFooOnNEXT_NEXT(t *testing.T) {
	id1TestAllCase(t, `{"B":"foo"}`, "NEXT,NEXT", map[string]any{"A": "foo"})
}

// JS: State node IDs > should go from {"B":"foo"} to {"B":"dot"} on NEXT_DOT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L70
func TestId_StateNodeIDs_ShouldGoFromBFooToBDotOnNEXT_DOT(t *testing.T) {
	id1TestAllCase(t, `{"B":"foo"}`, "NEXT_DOT", map[string]any{"B": "dot"})
}

// JS: State node IDs > should work with ID + relative path
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L76
func TestId_StateNodeIDs_ShouldWorkWithIDPlusRelativePath(t *testing.T) {
	machine := xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "foo",
		On: map[string]xs.Transitions{
			"ACTION": {{Target: "#bar.qux.quux"}},
		},
		States: xs.States{
			{Key: "foo", ID: "foo"},
			{
				Key:     "bar",
				ID:      "bar",
				Initial: "baz",
				States: xs.States{
					{Key: "baz"},
					{
						Key:     "qux",
						Initial: "quux",
						States: xs.States{
							{Key: "quux", ID: "#bar.qux.quux"},
						},
					},
				},
			},
		},
	})

	actorRef := xs.CreateActor(machine).Start()

	actorRef.Send(xs.Ev("ACTION"))

	assert.Equal(t, map[string]any{
		"bar": map[string]any{
			"qux": "quux",
		},
	}, actorRef.GetSnapshot().Value)
}

// JS: State node IDs > should work with keys that have escaped periods
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L117
func TestId_StateNodeIDs_ShouldWorkWithKeysThatHaveEscapedPeriods(t *testing.T) {
	machine := xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "start",
		States: xs.States{
			{Key: "start", On: map[string]xs.Transitions{
				"escaped":   {{Target: `foo\.bar`}},
				"unescaped": {{Target: "foo.bar"}},
			}},
			{Key: "foo.bar"},
			{
				Key:     "foo",
				Initial: "bar",
				States: xs.States{
					{Key: "bar"},
				},
			},
		},
	})

	initialState := xs.GetInitialSnapshot(machine)
	escapedState := xs.GetNextSnapshot(machine, initialState, xs.Ev("escaped"))

	assert.Equal(t, "foo.bar", escapedState.Value)

	unescapedState := xs.GetNextSnapshot(machine, initialState, xs.Ev("unescaped"))
	assert.Equal(t, map[string]any{"foo": "bar"}, unescapedState.Value)
}

// JS: State node IDs > should work with IDs that have escaped periods
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L150
func TestId_StateNodeIDs_ShouldWorkWithIDsThatHaveEscapedPeriods(t *testing.T) {
	machine := xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "start",
		States: xs.States{
			{Key: "start", On: map[string]xs.Transitions{
				"escaped":   {{Target: `#foo\.bar`}},
				"unescaped": {{Target: "#foo.bar"}},
			}},
			{Key: "stateWithDot", ID: "foo.bar"},
			{
				Key:     "foo",
				ID:      "foo",
				Initial: "bar",
				States: xs.States{
					{Key: "bar"},
				},
			},
		},
	})

	initialState := xs.GetInitialSnapshot(machine)
	escapedState := xs.GetNextSnapshot(machine, initialState, xs.Ev("escaped"))

	assert.Equal(t, "stateWithDot", escapedState.Value)

	unescapedState := xs.GetNextSnapshot(machine, initialState, xs.Ev("unescaped"))
	assert.Equal(t, map[string]any{"foo": "bar"}, unescapedState.Value)
}

// JS: State node IDs > should not treat escaped backslash as period's escape
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/id.test.ts#L186
func TestId_StateNodeIDs_ShouldNotTreatEscapedBackslashAsPeriodsEscape(t *testing.T) {
	machine := xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "start",
		States: xs.States{
			{Key: "start", On: map[string]xs.Transitions{
				// JS source '#some\\\\.thing' is the runtime string #some\\.thing
				"EV": {{Target: `#some\\.thing`}},
			}},
			// JS source 'some\\.thing' is the runtime string some\.thing
			{Key: "foo", ID: `some\.thing`},
			{
				Key: "bar",
				// JS source 'some\\' is the runtime string some\
				ID:      `some\`,
				Initial: "baz",
				States: xs.States{
					{Key: "baz"},
					{Key: "thing"},
				},
			},
		},
	})

	initialState := xs.GetInitialSnapshot(machine)
	escapedState := xs.GetNextSnapshot(machine, initialState, xs.Ev("EV"))

	assert.Equal(t, map[string]any{"bar": "thing"}, escapedState.Value)
}
