package xstate_test

import (
	"encoding/json"
	"regexp"
	"testing"

	xs "github.com/nguyenvanduocit/go-xstate/xstate"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// examples6161Machine mirrors the shared `machine` of describe('Example 6.16').
func examples6161Machine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Type: xs.Parallel,
		States: xs.States{
			{
				Key:     "A",
				Initial: "D",
				States: xs.States{
					{Key: "C", On: map[string]xs.Transitions{
						"2": {{Target: "D", Guard: xs.StateIn("#E")}},
					}},
					{Key: "D", On: map[string]xs.Transitions{"1": {{Target: "C"}}}},
				},
			},
			{
				Key:     "B",
				Initial: "F",
				States: xs.States{
					{Key: "E", ID: "E", On: map[string]xs.Transitions{"5": {{Target: "G"}}}},
					{Key: "F", On: map[string]xs.Transitions{"1": {{Target: "E"}}}},
					{Key: "G", On: map[string]xs.Transitions{"3": {{Target: "F"}}}},
				},
			},
		},
	})
}

// examples6161ResolveSerializedStateValue mirrors resolveSerializedStateValue
// from test/utils.ts.
func examples6161ResolveSerializedStateValue(t *testing.T, machine *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized[0] == '{' {
		var value any
		require.NoError(t, json.Unmarshal([]byte(serialized), &value))
		return machine.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return machine.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

var examples6161EventSplit = regexp.MustCompile(`,\s?`)

// examples6161TestMultiTransition mirrors testMultiTransition from test/utils.ts.
func examples6161TestMultiTransition(t *testing.T, machine *xs.StateMachine[any], fromState string, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	state := examples6161ResolveSerializedStateValue(t, machine, fromState)
	for _, eventType := range examples6161EventSplit.Split(eventTypes, -1) {
		state = xs.GetNextSnapshot[*xs.MachineSnapshot[any]](machine, state, xs.Ev(eventType))
	}
	return state
}

// examples6161TestAllCase mirrors the body of each it() generated by testAll
// from test/utils.ts. toState == nil mirrors `undefined` (no transition).
func examples6161TestAllCase(t *testing.T, fromState string, eventTypes string, toState xs.StateValue) {
	t.Helper()
	machine := examples6161Machine()
	resultState := examples6161TestMultiTransition(t, machine, fromState, eventTypes)

	switch ts := toState.(type) {
	case nil:
		// undefined means that the state didn't transition
		assert.Equal(t, examples6161ResolveSerializedStateValue(t, machine, fromState).Value, resultState.Value)
	case string:
		assert.True(t, xs.MatchesState(ts, resultState.Value))
	default:
		assert.Equal(t, toState, resultState.Value)
	}
}

// JS: Example 6.16 > should go from {"A":"D","B":"F"} to {"A":"C","B":"E"} on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L36
func TestExamples6_16_ShouldGoFromADBFToACBEOn1(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"D","B":"F"}`, "1", map[string]any{"A": "C", "B": "E"})
}

// JS: Example 6.16 > should go from {"A":"D","B":"F"} to undefined on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L37
func TestExamples6_16_ShouldGoFromADBFToUndefinedOn2(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"D","B":"F"}`, "2", nil)
}

// JS: Example 6.16 > should go from {"A":"D","B":"F"} to {"A":"C","B":"F"} on 1, 5, 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L38
func TestExamples6_16_ShouldGoFromADBFToACBFOn1_5_3(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"D","B":"F"}`, "1, 5, 3", map[string]any{"A": "C", "B": "F"})
}

// JS: Example 6.16 > should go from {"A":"C","B":"E"} to undefined on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L41
func TestExamples6_16_ShouldGoFromACBEToUndefinedOn1(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"C","B":"E"}`, "1", nil)
}

// JS: Example 6.16 > should go from {"A":"C","B":"E"} to {"A":"D","B":"E"} on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L42
func TestExamples6_16_ShouldGoFromACBEToADBEOn2(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"C","B":"E"}`, "2", map[string]any{"A": "D", "B": "E"})
}

// JS: Example 6.16 > should go from {"A":"C","B":"E"} to {"A":"C","B":"G"} on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L43
func TestExamples6_16_ShouldGoFromACBEToACBGOn5(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"C","B":"E"}`, "5", map[string]any{"A": "C", "B": "G"})
}

// JS: Example 6.16 > should go from {"A":"C","B":"G"} to undefined on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L46
func TestExamples6_16_ShouldGoFromACBGToUndefinedOn1(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"C","B":"G"}`, "1", nil)
}

// JS: Example 6.16 > should go from {"A":"C","B":"G"} to undefined on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L47
func TestExamples6_16_ShouldGoFromACBGToUndefinedOn2(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"C","B":"G"}`, "2", nil)
}

// JS: Example 6.16 > should go from {"A":"C","B":"G"} to {"A":"C","B":"F"} on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.16.test.ts#L48
func TestExamples6_16_ShouldGoFromACBGToACBFOn3(t *testing.T) {
	examples6161TestAllCase(t, `{"A":"C","B":"G"}`, "3", map[string]any{"A": "C", "B": "F"})
}

// examples6171ResolveSerializedStateValue mirrors resolveSerializedStateValue
// from test/utils.ts: a serialized value starting with '{' is JSON-parsed,
// otherwise it is used as a string state value.
func examples6171ResolveSerializedStateValue(t *testing.T, machine *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized != "" && serialized[0] == '{' {
		var value any
		if err := json.Unmarshal([]byte(serialized), &value); err != nil {
			t.Fatalf("invalid serialized state value %q: %v", serialized, err)
		}
		return machine.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return machine.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

var examples6171EventSplit = regexp.MustCompile(`,\s?`)

// examples6171TestMultiTransition mirrors testMultiTransition from test/utils.ts.
func examples6171TestMultiTransition(t *testing.T, machine *xs.StateMachine[any], fromState string, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	events := examples6171EventSplit.Split(eventTypes, -1)
	state := examples6171ResolveSerializedStateValue(t, machine, fromState)
	for _, eventType := range events {
		state = xs.GetNextSnapshot(machine, state, xs.Ev(eventType))
	}
	return state
}

// examples6171Example617Machine mirrors the machine of describe('Example 6.17').
func examples6171Example617Machine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "X",
		States: xs.States{
			{Key: "X", On: map[string]xs.Transitions{
				"1": {{Target: "Y"}},
				"2": {{Target: "Y.A.C"}}, // 6.18
				// 3: { Y: { A: 'C', B: 'F' } } // 6.19
				"4": {{Target: "Y.A.hist"}},
			}},
			{
				Key:  "Y",
				Type: xs.Parallel,
				States: xs.States{
					{Key: "A", Initial: "D", States: xs.States{
						{Key: "C"},
						{Key: "D"},
						{Key: "E"},
						{Key: "hist", Type: xs.History}, // history: true → shallow
					}},
					{Key: "B", Initial: "G", States: xs.States{
						{Key: "F"},
						{Key: "G"},
						{Key: "H"},
					}},
				},
				On: map[string]xs.Transitions{
					"back": {{Target: "X"}},
				},
			},
		},
	})
}

// examples6171JumpToIDMachine mirrors the machine of describe('Jump to ID').
func examples6171JumpToIDMachine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "X",
		States: xs.States{
			{Key: "X", ID: "X", On: map[string]xs.Transitions{
				"1": {{Target: "Y"}},
				"2": {{Target: "Y.A.C"}}, // 6.18
				// 3: { Y: { A: 'C', B: 'F' } } // 6.19
				"4": {{Target: "Y.A.hist"}},
			}},
			{
				Key:  "Y",
				Type: xs.Parallel,
				States: xs.States{
					{Key: "A", Initial: "D", States: xs.States{
						{Key: "C", On: map[string]xs.Transitions{
							"finish": {{Target: "#X"}},
						}},
						{Key: "D"},
						{Key: "E"},
						{Key: "hist", Type: xs.History}, // history: true → shallow
					}},
					{Key: "B", Initial: "G", States: xs.States{
						{Key: "F"},
						{Key: "G"},
						{Key: "H"},
					}},
				},
				On: map[string]xs.Transitions{
					"kill": {{Target: "#X"}},
				},
			},
		},
	})
}

// JS: Example 6.17 > should go from X to {"Y":{"A":"D","B":"G"}} on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L57
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L37
func TestExamples_Example617_ShouldGoFromXToYADBGOn1(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171Example617Machine(), "X", "1")
	assert.Equal(t, map[string]any{"Y": map[string]any{"A": "D", "B": "G"}}, resultState.Value)
}

// JS: Example 6.17 > should go from X to {"Y":{"A":"C","B":"G"}} on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L57
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L38
func TestExamples_Example617_ShouldGoFromXToYACBGOn2(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171Example617Machine(), "X", "2")
	assert.Equal(t, map[string]any{"Y": map[string]any{"A": "C", "B": "G"}}, resultState.Value)
}

// JS: Example 6.17 > should go from X to {"Y":{"A":"C","B":"G"}} on 2, back, 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L57
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L40
func TestExamples_Example617_ShouldGoFromXToYACBGOn2Back4(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171Example617Machine(), "X", "2, back, 4")
	assert.Equal(t, map[string]any{"Y": map[string]any{"A": "C", "B": "G"}}, resultState.Value)
}

// JS: Example 6.17 > should go from {"Y":{"A":"C","B":"G"}} to "X" on back
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L57
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L43
func TestExamples_Example617_ShouldGoFromYACBGToXOnBack(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171Example617Machine(), `{"Y":{"A":"C","B":"G"}}`, "back")
	assert.Equal(t, "X", resultState.Value)
}

// JS: Example 6.17 > should go from {"Y":{"A":"C"}} to "X" on back
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L57
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L46
func TestExamples_Example617_ShouldGoFromYACToXOnBack(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171Example617Machine(), `{"Y":{"A":"C"}}`, "back")
	assert.Equal(t, "X", resultState.Value)
}

// JS: Example 6.17 > should go from {"Y":{"B":"G"}} to "X" on back
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L57
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L49
func TestExamples_Example617_ShouldGoFromYBGToXOnBack(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171Example617Machine(), `{"Y":{"B":"G"}}`, "back")
	assert.Equal(t, "X", resultState.Value)
}

// JS: Jump to ID > should go from {"Y":{"B":"G"}} to "X" on kill
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L122
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L111
func TestExamples_JumpToID_ShouldGoFromYBGToXOnKill(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171JumpToIDMachine(), `{"Y":{"B":"G"}}`, "kill")
	assert.Equal(t, "X", resultState.Value)
}

// JS: Jump to ID > should go from {"Y":{"A":"C","B":"H"}} to "X" on finish
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L122
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.17.test.ts#L114
func TestExamples_JumpToID_ShouldGoFromYACBHToXOnFinish(t *testing.T) {
	resultState := examples6171TestMultiTransition(t, examples6171JumpToIDMachine(), `{"Y":{"A":"C","B":"H"}}`, "finish")
	assert.Equal(t, "X", resultState.Value)
}

// examples661Machine mirrors the describe-level `machine` in examples/6.6.test.ts:5-33.
func examples661Machine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "A",
		States: xs.States{
			{
				Key: "A",
				On: map[string]xs.Transitions{
					"3": {{Target: "B"}},
				},
				Initial: "D",
				States: xs.States{
					{Key: "C", On: map[string]xs.Transitions{
						"2": {{Target: "#B"}},
					}},
					{Key: "D", On: map[string]xs.Transitions{
						"1": {{Target: "C"}},
					}},
				},
			},
			{
				Key: "B",
				ID:  "B",
				On: map[string]xs.Transitions{
					"4": {{Target: "A.D"}},
				},
			},
		},
	})
}

// examples661ResolveSerializedStateValue mirrors resolveSerializedStateValue in test/utils.ts:10-16.
func examples661ResolveSerializedStateValue(t *testing.T, m *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized[0] == '{' {
		var value any
		if err := json.Unmarshal([]byte(serialized), &value); err != nil {
			t.Fatalf("invalid serialized state value %q: %v", serialized, err)
		}
		return m.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return m.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

// examples661TestMultiTransition mirrors testMultiTransition in test/utils.ts:18-44.
func examples661TestMultiTransition(t *testing.T, m *xs.StateMachine[any], fromState, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	state := examples661ResolveSerializedStateValue(t, m, fromState)
	for _, eventType := range regexp.MustCompile(`,\s?`).Split(eventTypes, -1) {
		state = xs.GetNextSnapshot(m, state, xs.Ev(eventType))
	}
	return state
}

// examples661AssertTransition mirrors the body of each it() generated by testAll in
// test/utils.ts:46-72. The expected table of this chunk has no `undefined` entries, so the
// "did not transition" branch is not needed.
func examples661AssertTransition(t *testing.T, fromState, eventTypes string, toState xs.StateValue) {
	t.Helper()
	m := examples661Machine()
	resultState := examples661TestMultiTransition(t, m, fromState, eventTypes)
	if s, ok := toState.(string); ok {
		assert.True(t, xs.MatchesState(s, resultState.Value))
	} else {
		assert.Equal(t, toState, resultState.Value)
	}
}

// JS: Example 6.6 > should go from A to {"A":"C"} on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L37
func TestExamples_Example66_ShouldGoFromAToACOn1(t *testing.T) {
	examples661AssertTransition(t, "A", "1", map[string]any{"A": "C"})
}

// JS: Example 6.6 > should go from A to {"A":"D"} on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L38
func TestExamples_Example66_ShouldGoFromAToADOn2(t *testing.T) {
	examples661AssertTransition(t, "A", "2", map[string]any{"A": "D"})
}

// JS: Example 6.6 > should go from A to "B" on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L39
func TestExamples_Example66_ShouldGoFromAToBOn3(t *testing.T) {
	examples661AssertTransition(t, "A", "3", "B")
}

// JS: Example 6.6 > should go from A to {"A":"D"} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L40
func TestExamples_Example66_ShouldGoFromAToADOn4(t *testing.T) {
	examples661AssertTransition(t, "A", "4", map[string]any{"A": "D"})
}

// JS: Example 6.6 > should go from B to "B" on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L43
func TestExamples_Example66_ShouldGoFromBToBOn1(t *testing.T) {
	examples661AssertTransition(t, "B", "1", "B")
}

// JS: Example 6.6 > should go from B to "B" on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L44
func TestExamples_Example66_ShouldGoFromBToBOn2(t *testing.T) {
	examples661AssertTransition(t, "B", "2", "B")
}

// JS: Example 6.6 > should go from B to "B" on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L45
func TestExamples_Example66_ShouldGoFromBToBOn3(t *testing.T) {
	examples661AssertTransition(t, "B", "3", "B")
}

// JS: Example 6.6 > should go from B to {"A":"D"} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L46
func TestExamples_Example66_ShouldGoFromBToADOn4(t *testing.T) {
	examples661AssertTransition(t, "B", "4", map[string]any{"A": "D"})
}

// JS: Example 6.6 > should go from {"A":"C"} to {"A":"C"} on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L49
func TestExamples_Example66_ShouldGoFromACToACOn1(t *testing.T) {
	examples661AssertTransition(t, `{"A":"C"}`, "1", map[string]any{"A": "C"})
}

// JS: Example 6.6 > should go from {"A":"C"} to "B" on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L50
func TestExamples_Example66_ShouldGoFromACToBOn2(t *testing.T) {
	examples661AssertTransition(t, `{"A":"C"}`, "2", "B")
}

// JS: Example 6.6 > should go from {"A":"C"} to "B" on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L51
func TestExamples_Example66_ShouldGoFromACToBOn3(t *testing.T) {
	examples661AssertTransition(t, `{"A":"C"}`, "3", "B")
}

// JS: Example 6.6 > should go from {"A":"C"} to {"A":"C"} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L52
func TestExamples_Example66_ShouldGoFromACToACOn4(t *testing.T) {
	examples661AssertTransition(t, `{"A":"C"}`, "4", map[string]any{"A": "C"})
}

// JS: Example 6.6 > should go from {"A":"D"} to {"A":"C"} on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L55
func TestExamples_Example66_ShouldGoFromADToACOn1(t *testing.T) {
	examples661AssertTransition(t, `{"A":"D"}`, "1", map[string]any{"A": "C"})
}

// JS: Example 6.6 > should go from {"A":"D"} to {"A":"D"} on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L56
func TestExamples_Example66_ShouldGoFromADToADOn2(t *testing.T) {
	examples661AssertTransition(t, `{"A":"D"}`, "2", map[string]any{"A": "D"})
}

// JS: Example 6.6 > should go from {"A":"D"} to "B" on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L57
func TestExamples_Example66_ShouldGoFromADToBOn3(t *testing.T) {
	examples661AssertTransition(t, `{"A":"D"}`, "3", "B")
}

// JS: Example 6.6 > should go from {"A":"D"} to {"A":"D"} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.6.test.ts#L58
func TestExamples_Example66_ShouldGoFromADToADOn4(t *testing.T) {
	examples661AssertTransition(t, `{"A":"D"}`, "4", map[string]any{"A": "D"})
}

// examples681Machine mirrors the shared `machine` of describe('Example 6.8').
func examples681Machine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "A",
		States: xs.States{
			{
				Key:     "A",
				On:      map[string]xs.Transitions{"6": {{Target: "F"}}},
				Initial: "B",
				States: xs.States{
					{Key: "B", On: map[string]xs.Transitions{"1": {{Target: "C"}}}},
					{Key: "C", On: map[string]xs.Transitions{"2": {{Target: "E"}}}},
					{Key: "D", On: map[string]xs.Transitions{"3": {{Target: "B"}}}},
					{Key: "E", On: map[string]xs.Transitions{
						"4": {{Target: "B"}},
						"5": {{Target: "D"}},
					}},
					// history: true → shallow history
					{Key: "hist", Type: xs.History, History: xs.Shallow},
				},
			},
			{
				Key: "F",
				On:  map[string]xs.Transitions{"5": {{Target: "A.hist"}}},
			},
		},
	})
}

// examples681ResolveSerializedStateValue mirrors resolveSerializedStateValue
// from test/utils.ts.
func examples681ResolveSerializedStateValue(t *testing.T, machine *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized[0] == '{' {
		var value any
		require.NoError(t, json.Unmarshal([]byte(serialized), &value))
		return machine.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return machine.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

var examples681EventSplit = regexp.MustCompile(`,\s?`)

// examples681TestMultiTransition mirrors testMultiTransition from test/utils.ts.
func examples681TestMultiTransition(t *testing.T, machine *xs.StateMachine[any], fromState string, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	state := examples681ResolveSerializedStateValue(t, machine, fromState)
	for _, eventType := range examples681EventSplit.Split(eventTypes, -1) {
		state = xs.GetNextSnapshot[*xs.MachineSnapshot[any]](machine, state, xs.Ev(eventType))
	}
	return state
}

// examples681TestAllCase mirrors the body of each it() generated by testAll
// from test/utils.ts. toState == nil mirrors `undefined` (no transition).
func examples681TestAllCase(t *testing.T, fromState string, eventTypes string, toState xs.StateValue) {
	t.Helper()
	machine := examples681Machine()
	resultState := examples681TestMultiTransition(t, machine, fromState, eventTypes)

	switch ts := toState.(type) {
	case nil:
		// undefined means that the state didn't transition
		assert.Equal(t, examples681ResolveSerializedStateValue(t, machine, fromState).Value, resultState.Value)
	case string:
		assert.True(t, xs.MatchesState(ts, resultState.Value))
	default:
		assert.Equal(t, toState, resultState.Value)
	}
}

// JS: Example 6.8 > should go from A to "A.C" on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L39
func TestExamples6_8_ShouldGoFromAToACOn1(t *testing.T) {
	examples681TestAllCase(t, "A", "1", "A.C")
}

// JS: Example 6.8 > should go from A to "F" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L40
func TestExamples6_8_ShouldGoFromAToFOn6(t *testing.T) {
	examples681TestAllCase(t, "A", "6", "F")
}

// JS: Example 6.8 > should go from {"A":"B"} to "A.C" on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L43
func TestExamples6_8_ShouldGoFromABToACOn1(t *testing.T) {
	examples681TestAllCase(t, `{"A":"B"}`, "1", "A.C")
}

// JS: Example 6.8 > should go from {"A":"B"} to "F" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L44
func TestExamples6_8_ShouldGoFromABToFOn6(t *testing.T) {
	examples681TestAllCase(t, `{"A":"B"}`, "6", "F")
}

// JS: Example 6.8 > should go from {"A":"B"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L45
func TestExamples6_8_ShouldGoFromABToUndefinedOnFAKE(t *testing.T) {
	examples681TestAllCase(t, `{"A":"B"}`, "FAKE", nil)
}

// JS: Example 6.8 > should go from {"A":"C"} to "A.E" on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L48
func TestExamples6_8_ShouldGoFromACToAEOn2(t *testing.T) {
	examples681TestAllCase(t, `{"A":"C"}`, "2", "A.E")
}

// JS: Example 6.8 > should go from {"A":"C"} to "F" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L49
func TestExamples6_8_ShouldGoFromACToFOn6(t *testing.T) {
	examples681TestAllCase(t, `{"A":"C"}`, "6", "F")
}

// JS: Example 6.8 > should go from {"A":"C"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L50
func TestExamples6_8_ShouldGoFromACToUndefinedOnFAKE(t *testing.T) {
	examples681TestAllCase(t, `{"A":"C"}`, "FAKE", nil)
}

// JS: Example 6.8 > should go from {"A":"D"} to "A.B" on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L53
func TestExamples6_8_ShouldGoFromADToABOn3(t *testing.T) {
	examples681TestAllCase(t, `{"A":"D"}`, "3", "A.B")
}

// JS: Example 6.8 > should go from {"A":"D"} to "F" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L54
func TestExamples6_8_ShouldGoFromADToFOn6(t *testing.T) {
	examples681TestAllCase(t, `{"A":"D"}`, "6", "F")
}

// JS: Example 6.8 > should go from {"A":"D"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L55
func TestExamples6_8_ShouldGoFromADToUndefinedOnFAKE(t *testing.T) {
	examples681TestAllCase(t, `{"A":"D"}`, "FAKE", nil)
}

// JS: Example 6.8 > should go from {"A":"E"} to "A.B" on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L58
func TestExamples6_8_ShouldGoFromAEToABOn4(t *testing.T) {
	examples681TestAllCase(t, `{"A":"E"}`, "4", "A.B")
}

// JS: Example 6.8 > should go from {"A":"E"} to "A.D" on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L59
func TestExamples6_8_ShouldGoFromAEToADOn5(t *testing.T) {
	examples681TestAllCase(t, `{"A":"E"}`, "5", "A.D")
}

// JS: Example 6.8 > should go from {"A":"E"} to "F" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L60
func TestExamples6_8_ShouldGoFromAEToFOn6(t *testing.T) {
	examples681TestAllCase(t, `{"A":"E"}`, "6", "F")
}

// JS: Example 6.8 > should go from {"A":"E"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L61
func TestExamples6_8_ShouldGoFromAEToUndefinedOnFAKE(t *testing.T) {
	examples681TestAllCase(t, `{"A":"E"}`, "FAKE", nil)
}

// JS: Example 6.8 > should go from F to "A.B" on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L64
func TestExamples6_8_ShouldGoFromFToABOn5(t *testing.T) {
	examples681TestAllCase(t, "F", "5", "A.B")
}

// JS: Example 6.8 > should respect the history mechanism
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.8.test.ts#L70
func TestExamples6_8_ShouldRespectTheHistoryMechanism(t *testing.T) {
	actorRef := xs.CreateActor(examples681Machine()).Start()

	actorRef.Send(xs.Ev("1"))
	actorRef.Send(xs.Ev("6"))
	actorRef.Send(xs.Ev("5"))

	assert.Equal(t, map[string]any{"A": "C"}, actorRef.GetSnapshot().Value)
}

// examples691Machine mirrors the describe-level `machine` in examples/6.9.test.ts:5-51.
// JS `history: true` resolves to a shallow history node (StateNode.ts:192,227).
func examples691Machine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "A",
		States: xs.States{
			{
				Key: "A",
				On: map[string]xs.Transitions{
					"6": {{Target: "H"}},
				},
				Initial: "B",
				States: xs.States{
					{
						Key:     "B",
						Initial: "E",
						On: map[string]xs.Transitions{
							"5": {{Target: "C"}},
						},
						States: xs.States{
							{Key: "D"},
							{Key: "E", On: map[string]xs.Transitions{
								"3": {{Target: "D"}},
							}},
						},
					},
					{
						Key:     "C",
						Initial: "G",
						On: map[string]xs.Transitions{
							"4": {{Target: "B.E"}},
						},
						States: xs.States{
							{Key: "F"},
							{Key: "G", On: map[string]xs.Transitions{
								"2": {{Target: "F"}},
							}},
						},
					},
					{Key: "hist", Type: xs.History, History: xs.Shallow},
					{Key: "deepHist", Type: xs.History, History: xs.Deep},
				},
			},
			{
				Key: "H",
				On: map[string]xs.Transitions{
					"1": {{Target: "A.hist"}},
					"7": {{Target: "A.deepHist"}}, // 6.10
				},
			},
		},
	})
}

// examples691ResolveSerializedStateValue mirrors resolveSerializedStateValue in test/utils.ts:10-16.
func examples691ResolveSerializedStateValue(t *testing.T, machine *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized[0] == '{' {
		var value any
		require.NoError(t, json.Unmarshal([]byte(serialized), &value))
		return machine.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return machine.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

var examples691EventSplit = regexp.MustCompile(`,\s?`)

// examples691TestMultiTransition mirrors testMultiTransition in test/utils.ts:18-44.
func examples691TestMultiTransition(t *testing.T, machine *xs.StateMachine[any], fromState string, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	state := examples691ResolveSerializedStateValue(t, machine, fromState)
	for _, eventType := range examples691EventSplit.Split(eventTypes, -1) {
		state = xs.GetNextSnapshot[*xs.MachineSnapshot[any]](machine, state, xs.Ev(eventType))
	}
	return state
}

// examples691TestAllCase mirrors the body of each it() generated by testAll in
// test/utils.ts:46-72. toState == nil mirrors `undefined` (no transition).
func examples691TestAllCase(t *testing.T, fromState string, eventTypes string, toState xs.StateValue) {
	t.Helper()
	machine := examples691Machine()
	resultState := examples691TestMultiTransition(t, machine, fromState, eventTypes)

	switch ts := toState.(type) {
	case nil:
		// undefined means that the state didn't transition
		assert.Equal(t, examples691ResolveSerializedStateValue(t, machine, fromState).Value, resultState.Value)
	case string:
		assert.True(t, xs.MatchesState(ts, resultState.Value))
	default:
		assert.Equal(t, toState, resultState.Value)
	}
}

// JS: Example 6.9 > should go from A to {"A":{"B":"D"}} on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L55
func TestExamples_Example69_ShouldGoFromAToABDOn3(t *testing.T) {
	examples691TestAllCase(t, "A", "3", map[string]any{"A": map[string]any{"B": "D"}})
}

// JS: Example 6.9 > should go from A to {"A":{"C":"G"}} on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L56
func TestExamples_Example69_ShouldGoFromAToACGOn5(t *testing.T) {
	examples691TestAllCase(t, "A", "5", map[string]any{"A": map[string]any{"C": "G"}})
}

// JS: Example 6.9 > should go from A to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L57
func TestExamples_Example69_ShouldGoFromAToHOn6(t *testing.T) {
	examples691TestAllCase(t, "A", "6", "H")
}

// JS: Example 6.9 > should go from A to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L58
func TestExamples_Example69_ShouldGoFromAToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, "A", "FAKE", nil)
}

// JS: Example 6.9 > should go from {"A":"B"} to {"A":{"B":"D"}} on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L61
func TestExamples_Example69_ShouldGoFromABToABDOn3(t *testing.T) {
	examples691TestAllCase(t, `{"A":"B"}`, "3", map[string]any{"A": map[string]any{"B": "D"}})
}

// JS: Example 6.9 > should go from {"A":"B"} to {"A":{"C":"G"}} on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L62
func TestExamples_Example69_ShouldGoFromABToACGOn5(t *testing.T) {
	examples691TestAllCase(t, `{"A":"B"}`, "5", map[string]any{"A": map[string]any{"C": "G"}})
}

// JS: Example 6.9 > should go from {"A":"B"} to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L63
func TestExamples_Example69_ShouldGoFromABToHOn6(t *testing.T) {
	examples691TestAllCase(t, `{"A":"B"}`, "6", "H")
}

// JS: Example 6.9 > should go from {"A":"B"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L64
func TestExamples_Example69_ShouldGoFromABToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, `{"A":"B"}`, "FAKE", nil)
}

// JS: Example 6.9 > should go from {"A":"B"} to {"A":{"C":"G"}} on 5, 6, 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L67
func TestExamples_Example69_ShouldGoFromABToACGOn5_6_1(t *testing.T) {
	examples691TestAllCase(t, `{"A":"B"}`, "5, 6, 1", map[string]any{"A": map[string]any{"C": "G"}})
}

// JS: Example 6.9 > should go from {"A":"B"} to {"A":{"B":"E"}} on 3, 6, 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L68
func TestExamples_Example69_ShouldGoFromABToABEOn3_6_1(t *testing.T) {
	examples691TestAllCase(t, `{"A":"B"}`, "3, 6, 1", map[string]any{"A": map[string]any{"B": "E"}})
}

// JS: Example 6.9 > should go from {"A":"C"} to {"A":{"C":"F"}} on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L72
func TestExamples_Example69_ShouldGoFromACToACFOn2(t *testing.T) {
	examples691TestAllCase(t, `{"A":"C"}`, "2", map[string]any{"A": map[string]any{"C": "F"}})
}

// JS: Example 6.9 > should go from {"A":"C"} to {"A":{"B":"E"}} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L73
func TestExamples_Example69_ShouldGoFromACToABEOn4(t *testing.T) {
	examples691TestAllCase(t, `{"A":"C"}`, "4", map[string]any{"A": map[string]any{"B": "E"}})
}

// JS: Example 6.9 > should go from {"A":"C"} to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L74
func TestExamples_Example69_ShouldGoFromACToHOn6(t *testing.T) {
	examples691TestAllCase(t, `{"A":"C"}`, "6", "H")
}

// JS: Example 6.9 > should go from {"A":"C"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L75
func TestExamples_Example69_ShouldGoFromACToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, `{"A":"C"}`, "FAKE", nil)
}

// JS: Example 6.9 > should go from {"A":"C"} to {"A":{"C":"G"}} on 6, 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L76
func TestExamples_Example69_ShouldGoFromACToACGOn6_1(t *testing.T) {
	examples691TestAllCase(t, `{"A":"C"}`, "6, 1", map[string]any{"A": map[string]any{"C": "G"}})
}

// JS: Example 6.9 > should go from {"A":"C"} to {"A":{"B":"E"}} on 4, 6, 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L77
func TestExamples_Example69_ShouldGoFromACToABEOn4_6_1(t *testing.T) {
	examples691TestAllCase(t, `{"A":"C"}`, "4, 6, 1", map[string]any{"A": map[string]any{"B": "E"}})
}

// JS: Example 6.9 > should go from {"A":{"B":"D"}} to {"A":{"C":"G"}} on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L80
func TestExamples_Example69_ShouldGoFromABDToACGOn5(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"D"}}`, "5", map[string]any{"A": map[string]any{"C": "G"}})
}

// JS: Example 6.9 > should go from {"A":{"B":"D"}} to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L81
func TestExamples_Example69_ShouldGoFromABDToHOn6(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"D"}}`, "6", "H")
}

// JS: Example 6.9 > should go from {"A":{"B":"D"}} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L82
func TestExamples_Example69_ShouldGoFromABDToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"D"}}`, "FAKE", nil)
}

// JS: Example 6.9 > should go from {"A":{"B":"E"}} to {"A":{"B":"D"}} on 3
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L85
func TestExamples_Example69_ShouldGoFromABEToABDOn3(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"E"}}`, "3", map[string]any{"A": map[string]any{"B": "D"}})
}

// JS: Example 6.9 > should go from {"A":{"B":"E"}} to {"A":{"C":"G"}} on 5
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L86
func TestExamples_Example69_ShouldGoFromABEToACGOn5(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"E"}}`, "5", map[string]any{"A": map[string]any{"C": "G"}})
}

// JS: Example 6.9 > should go from {"A":{"B":"E"}} to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L87
func TestExamples_Example69_ShouldGoFromABEToHOn6(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"E"}}`, "6", "H")
}

// JS: Example 6.9 > should go from {"A":{"B":"E"}} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L88
func TestExamples_Example69_ShouldGoFromABEToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"B":"E"}}`, "FAKE", nil)
}

// JS: Example 6.9 > should go from {"A":{"C":"F"}} to {"A":{"B":"E"}} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L91
func TestExamples_Example69_ShouldGoFromACFToABEOn4(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"F"}}`, "4", map[string]any{"A": map[string]any{"B": "E"}})
}

// JS: Example 6.9 > should go from {"A":{"C":"F"}} to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L92
func TestExamples_Example69_ShouldGoFromACFToHOn6(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"F"}}`, "6", "H")
}

// JS: Example 6.9 > should go from {"A":{"C":"F"}} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L93
func TestExamples_Example69_ShouldGoFromACFToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"F"}}`, "FAKE", nil)
}

// JS: Example 6.9 > should go from {"A":{"C":"G"}} to {"A":{"C":"F"}} on 2
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L96
func TestExamples_Example69_ShouldGoFromACGToACFOn2(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"G"}}`, "2", map[string]any{"A": map[string]any{"C": "F"}})
}

// JS: Example 6.9 > should go from {"A":{"C":"G"}} to {"A":{"B":"E"}} on 4
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L97
func TestExamples_Example69_ShouldGoFromACGToABEOn4(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"G"}}`, "4", map[string]any{"A": map[string]any{"B": "E"}})
}

// JS: Example 6.9 > should go from {"A":{"C":"G"}} to "H" on 6
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L98
func TestExamples_Example69_ShouldGoFromACGToHOn6(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"G"}}`, "6", "H")
}

// JS: Example 6.9 > should go from {"A":{"C":"G"}} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L99
func TestExamples_Example69_ShouldGoFromACGToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, `{"A":{"C":"G"}}`, "FAKE", nil)
}

// JS: Example 6.9 > should go from H to {"A":{"B":"E"}} on 1
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L102
func TestExamples_Example69_ShouldGoFromHToABEOn1(t *testing.T) {
	examples691TestAllCase(t, "H", "1", map[string]any{"A": map[string]any{"B": "E"}})
}

// JS: Example 6.9 > should go from H to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/6.9.test.ts#L103
func TestExamples_Example69_ShouldGoFromHToUndefinedOnFAKE(t *testing.T) {
	examples691TestAllCase(t, "H", "FAKE", nil)
}

// examplesCd1Machine mirrors the describe-level `machine` in examples/cd.test.ts:5-48.
func examplesCd1Machine() *xs.StateMachine[any] {
	return xs.CreateMachine(xs.MachineConfig[any]{
		Initial: "not_loaded",
		States: xs.States{
			{
				Key: "not_loaded",
				On: map[string]xs.Transitions{
					"INSERT_CD": {{Target: "loaded"}},
				},
			},
			{
				Key:     "loaded",
				Initial: "stopped",
				On: map[string]xs.Transitions{
					"EJECT": {{Target: "not_loaded"}},
				},
				States: xs.States{
					{
						Key: "stopped",
						On: map[string]xs.Transitions{
							"PLAY": {{Target: "playing"}},
						},
					},
					{
						Key: "playing",
						On: map[string]xs.Transitions{
							"STOP":        {{Target: "stopped"}},
							"EXPIRED_END": {{Target: "stopped"}},
							"EXPIRED_MID": {{Target: "playing"}},
							"PAUSE":       {{Target: "paused"}},
						},
					},
					{
						Key:     "paused",
						Initial: "not_blank",
						States: xs.States{
							{Key: "blank", On: map[string]xs.Transitions{"TIMER": {{Target: "not_blank"}}}},
							{Key: "not_blank", On: map[string]xs.Transitions{"TIMER": {{Target: "blank"}}}},
						},
						On: map[string]xs.Transitions{
							"PAUSE": {{Target: "playing"}},
							"PLAY":  {{Target: "playing"}},
							"STOP":  {{Target: "stopped"}},
						},
					},
				},
			},
		},
	})
}

// examplesCd1ResolveSerializedStateValue mirrors resolveSerializedStateValue in test/utils.ts:10-16.
func examplesCd1ResolveSerializedStateValue(t *testing.T, machine *xs.StateMachine[any], serialized string) *xs.MachineSnapshot[any] {
	t.Helper()
	if serialized[0] == '{' {
		var value any
		require.NoError(t, json.Unmarshal([]byte(serialized), &value))
		return machine.ResolveState(xs.ResolveStateConfig[any]{Value: value, Context: map[string]any{}})
	}
	return machine.ResolveState(xs.ResolveStateConfig[any]{Value: serialized, Context: map[string]any{}})
}

var examplesCd1EventSplit = regexp.MustCompile(`,\s?`)

// examplesCd1TestMultiTransition mirrors testMultiTransition in test/utils.ts:18-44.
func examplesCd1TestMultiTransition(t *testing.T, machine *xs.StateMachine[any], fromState, eventTypes string) *xs.MachineSnapshot[any] {
	t.Helper()
	state := examplesCd1ResolveSerializedStateValue(t, machine, fromState)
	for _, eventType := range examplesCd1EventSplit.Split(eventTypes, -1) {
		state = xs.GetNextSnapshot[*xs.MachineSnapshot[any]](machine, state, xs.Ev(eventType))
	}
	return state
}

// examplesCd1TestAllCase mirrors the body of each it() generated by testAll in
// test/utils.ts:46-72. toState == nil mirrors `undefined` (no transition).
func examplesCd1TestAllCase(t *testing.T, fromState, eventTypes string, toState xs.StateValue) {
	t.Helper()
	machine := examplesCd1Machine()
	resultState := examplesCd1TestMultiTransition(t, machine, fromState, eventTypes)

	switch ts := toState.(type) {
	case nil:
		// undefined means that the state didn't transition
		assert.Equal(t, examplesCd1ResolveSerializedStateValue(t, machine, fromState).Value, resultState.Value)
	case string:
		assert.True(t, xs.MatchesState(ts, resultState.Value))
	default:
		assert.Equal(t, toState, resultState.Value)
	}
}

// JS: Example: CD Player > should go from not_loaded to "loaded.stopped" on INSERT_CD
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L52
func TestExamples_CDPlayer_ShouldGoFromNotLoadedToLoadedStoppedOnINSERTCD(t *testing.T) {
	examplesCd1TestAllCase(t, "not_loaded", "INSERT_CD", "loaded.stopped")
}

// JS: Example: CD Player > should go from not_loaded to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L53
func TestExamples_CDPlayer_ShouldGoFromNotLoadedToUndefinedOnFAKE(t *testing.T) {
	examplesCd1TestAllCase(t, "not_loaded", "FAKE", nil)
}

// JS: Example: CD Player > should go from loaded to "not_loaded" on EJECT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L56
func TestExamples_CDPlayer_ShouldGoFromLoadedToNotLoadedOnEJECT(t *testing.T) {
	examplesCd1TestAllCase(t, "loaded", "EJECT", "not_loaded")
}

// JS: Example: CD Player > should go from loaded to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L57
func TestExamples_CDPlayer_ShouldGoFromLoadedToUndefinedOnFAKE(t *testing.T) {
	examplesCd1TestAllCase(t, "loaded", "FAKE", nil)
}

// JS: Example: CD Player > should go from {"loaded":"stopped"} to "loaded.playing" on PLAY
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L60
func TestExamples_CDPlayer_ShouldGoFromLoadedStoppedToLoadedPlayingOnPLAY(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"stopped"}`, "PLAY", "loaded.playing")
}

// JS: Example: CD Player > should go from {"loaded":"stopped"} to "not_loaded" on EJECT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L61
func TestExamples_CDPlayer_ShouldGoFromLoadedStoppedToNotLoadedOnEJECT(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"stopped"}`, "EJECT", "not_loaded")
}

// JS: Example: CD Player > should go from {"loaded":"stopped"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L62
func TestExamples_CDPlayer_ShouldGoFromLoadedStoppedToUndefinedOnFAKE(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"stopped"}`, "FAKE", nil)
}

// JS: Example: CD Player > should go from {"loaded":"playing"} to "loaded.playing" on EXPIRED_MID
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L65
func TestExamples_CDPlayer_ShouldGoFromLoadedPlayingToLoadedPlayingOnEXPIREDMID(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"playing"}`, "EXPIRED_MID", "loaded.playing")
}

// JS: Example: CD Player > should go from {"loaded":"playing"} to "loaded.stopped" on EXPIRED_END
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L66
func TestExamples_CDPlayer_ShouldGoFromLoadedPlayingToLoadedStoppedOnEXPIREDEND(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"playing"}`, "EXPIRED_END", "loaded.stopped")
}

// JS: Example: CD Player > should go from {"loaded":"playing"} to "loaded.stopped" on STOP
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L67
func TestExamples_CDPlayer_ShouldGoFromLoadedPlayingToLoadedStoppedOnSTOP(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"playing"}`, "STOP", "loaded.stopped")
}

// JS: Example: CD Player > should go from {"loaded":"playing"} to "not_loaded" on EJECT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L68
func TestExamples_CDPlayer_ShouldGoFromLoadedPlayingToNotLoadedOnEJECT(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"playing"}`, "EJECT", "not_loaded")
}

// JS: Example: CD Player > should go from {"loaded":"playing"} to "loaded.paused.not_blank" on PAUSE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L69
func TestExamples_CDPlayer_ShouldGoFromLoadedPlayingToLoadedPausedNotBlankOnPAUSE(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"playing"}`, "PAUSE", "loaded.paused.not_blank")
}

// JS: Example: CD Player > should go from {"loaded":"playing"} to undefined on FAKE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L70
func TestExamples_CDPlayer_ShouldGoFromLoadedPlayingToUndefinedOnFAKE(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"playing"}`, "FAKE", nil)
}

// JS: Example: CD Player > should go from {"loaded":"paused"} to "loaded.playing" on PAUSE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L73
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedToLoadedPlayingOnPAUSE(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"paused"}`, "PAUSE", "loaded.playing")
}

// JS: Example: CD Player > should go from {"loaded":"paused"} to "loaded.playing" on PLAY
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L74
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedToLoadedPlayingOnPLAY(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"paused"}`, "PLAY", "loaded.playing")
}

// JS: Example: CD Player > should go from {"loaded":"paused"} to "loaded.paused.blank" on TIMER
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L75
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedToLoadedPausedBlankOnTIMER(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"paused"}`, "TIMER", "loaded.paused.blank")
}

// JS: Example: CD Player > should go from {"loaded":"paused"} to "not_loaded" on EJECT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L76
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedToNotLoadedOnEJECT(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"paused"}`, "EJECT", "not_loaded")
}

// JS: Example: CD Player > should go from {"loaded":"paused"} to "loaded.stopped" on STOP
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L77
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedToLoadedStoppedOnSTOP(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":"paused"}`, "STOP", "loaded.stopped")
}

// JS: Example: CD Player > should go from {"loaded":{"paused": "blank"}} to "loaded.playing" on PAUSE
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L80
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedBlankToLoadedPlayingOnPAUSE(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":{"paused": "blank"}}`, "PAUSE", "loaded.playing")
}

// JS: Example: CD Player > should go from {"loaded":{"paused": "blank"}} to "loaded.playing" on PLAY
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L81
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedBlankToLoadedPlayingOnPLAY(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":{"paused": "blank"}}`, "PLAY", "loaded.playing")
}

// JS: Example: CD Player > should go from {"loaded":{"paused": "blank"}} to "loaded.paused.not_blank" on TIMER
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L82
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedBlankToLoadedPausedNotBlankOnTIMER(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":{"paused": "blank"}}`, "TIMER", "loaded.paused.not_blank")
}

// JS: Example: CD Player > should go from {"loaded":{"paused": "blank"}} to "not_loaded" on EJECT
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L83
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedBlankToNotLoadedOnEJECT(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":{"paused": "blank"}}`, "EJECT", "not_loaded")
}

// JS: Example: CD Player > should go from {"loaded":{"paused": "blank"}} to "loaded.stopped" on STOP
// JS test: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/utils.ts#L54
// JS case: https://github.com/statelyai/xstate/blob/38dcaffb20ec7f3cbb10e6161d8f0ebacca33701/packages/core/test/examples/cd.test.ts#L84
func TestExamples_CDPlayer_ShouldGoFromLoadedPausedBlankToLoadedStoppedOnSTOP(t *testing.T) {
	examplesCd1TestAllCase(t, `{"loaded":{"paused": "blank"}}`, "STOP", "loaded.stopped")
}
